when retrieving queue name, check for 'queue_as' which is how ActiveJob defines queue names
resque/resque pull request #1713
Opened 2020-04-05 21:42 UTC by josh-m-sharpe

This fixes an issue when queueing jobs from resque-scheduler's Scheudle page.  Without this change, resque is unable to identify the queue to drop the job on.

ActiveJob details:

https://api.rubyonrails.org/classes/ActiveJob/QueueName/ClassMethods.html#method-i-queue_as
https://github.com/rails/rails/blob/157920aead96865e3135f496c09ace607d5620dc/activejob/lib/active_job/queue_name.rb#L41
https://github.com/rails/rails/blob/157920aead96865e3135f496c09ace607d5620dc/activejob/lib/active_job/queue_name.rb#L62

2020-04-08 21:53 UTC, rafaelfranca commented
`queue_as` is how Active Job defines the queue, not how you get the value. Should not this being calling `queued_name`?

But either way, Resque should not know anything about Active Job.

Why do you think this change is necessary? The Active Job adapter already set the correct queue name to Resque. https://github.com/rails/rails/blob/855c9897eb98ea4d77ec5036d15cdd1764698838/activejob/lib/active_job/queue_adapters/resque_adapter.rb#L33

2020-04-08 22:31 UTC, josh-m-sharpe commented
Branch updated to use `queue_name`.  I needed this to allow resque-scheduler to correctly queue ActiveJobs: https://github.com/resque/resque-scheduler/blob/master/lib/resque/scheduler/server.rb#L149 - that plugin uses `Resque. queue_from_class` in a couple other places as well.

I suspect this fix is probably still necessary in this context given that `resque-scheduler` is a plugin for `resque` and not `ActiveJob`... maybe?

2020-04-08 22:59 UTC, josh-m-sharpe commented
Yea, I think the issue (which has nothing to do with resque-scheudler) is that `Resque.queue_from_class` returns `false` for ActiveJob jobs:

```
$ cat app/jobs/standard_job.rb
class StandardJob < ApplicationJob
  queue_as :default

  def perform(*args)
    sleep 0.1
  end
end

$ cat app/jobs/application_job.rb
class ApplicationJob < ActiveJob::Base
end

$ rc
Loading development environment (Rails 6.0.2.2)
[1] pry(main)> Resque.queue_from_class(StandardError)
=> false
```

2020-04-08 23:15 UTC, rafaelfranca commented
That makes sense. That happen because resque doesn't, and should not, know about Active Job. So ` Resque.queue_from_class(StandardJob)` should return `false`.

Also, we can't determine the queue name for a subclass of `ActiveJob::Base` using the class. We need to use the instance.

That being said, in order to expose the queue for a job we will need to make significant changes to the Resque plugin in Active Job to wrap each job in a class like we do in the Sidekiq adapter.

2020-04-08 23:46 UTC, josh-m-sharpe commented
> Also, we can't determine the queue name for a subclass of ActiveJob::Base using the class. We need to use the instance.

This PR is doing: `klass.new.queue_name` so I believe it is pulling the correct queue name.

Apologies, but I'm not sure I follow what you are saying here:

> That being said, in order to expose the queue for a job we will need to make significant changes to the Resque plugin in Active Job to wrap each job in a class like we do in the Sidekiq adapter.

2021-09-16 15:53 UTC, iloveitaly requested changes
@josh-m-sharpe Although I agree with rafaelfranca in principle—that resque shouldn't know about ActiveJob—I think it's a better UX to add some light bindings / support for ActiveJob given that's a very popular pattern.

@rafaelfranca Could you explain further why "we will need to make significant changes to the Resque plugin in Active Job"? I'm not seeing any issues here, but I don't have as much experience with ActiveJob.

2025-09-29 19:27 UTC, varyonic commented on lib/resque.rb
> +    (klass.respond_to?(:queue_name) && klass.new.queue_name)
Thank you for this, I found it useful. Has it been superseded by another solution or shall I fork/rebase and resubmit?

2026-09-10 20:22 UTC, PatrickTulskie commented
Actually took a crack at trying to get this in earlier, but it started to fall apart when I got deeper into it. Really thought this would be a layup given how ActiveJob's adapter is now in resque so resque (kinda) knows about ActiveJob.

When testing this PR and #1965 we found that in the case of scheduler, it just delayed the crash. I think the original issue is something we actually need to address in resque-scheduler and there is a potential feature we could add to resque to make life a little easier there as well. My agent wrote a lengthy analysis of this in #1965 for anyone that cares to read a wall of text.

That said, we opened up two related issues to hopefully address some of this in later releases. I appreciate the work everyone put into this, and we'll be revisiting this shortly. Thanks!

2026-09-10 20:22 UTC, closed without merging