Add button for deleting jobs from queue
resque/resque pull request #1732
Opened 2020-10-30 16:15 UTC by h3nnn4n

More than once I was required to either remove one pending job from Resque, or all jobs of a given class. For both cases I had to access the production server and run a custom script, which is not ideal. Based on that, this PR makes two changes:
1) Adds a dropdown with the list of all job classes in a queue and a button that removes all jobs of the selected class from the queue.
2) A button next to a pending job to delete that specific job

Here is a screenshot of how it looks:
![Resque](https://user-images.githubusercontent.com/7543345/97729213-3a9f8b00-1ab1-11eb-8de9-6f217827d556.png)

Some notes:
* To properly support `ActiveJob` jobs I had to add some checks to fetch the class from the payload
* The button to remove a job will delete all jobs matching class and args. I could not find a better way to do this.

2020-10-30 16:33 UTC, eduardoborba approved these changes

2020-10-30 16:33 UTC, eduardoborba commented on lib/resque/server/views/job_class.erb
> +  <input id="job_args" name="job_args" type="hidden" value=<%=job['args'].to_json%> />
```suggestion
  <input id="job_class" name="job_class" type="hidden" value=<%= job['class'] %> />
  <input id="job_args" name="job_args" type="hidden" value=<%= job['args'].to_json %> />
```

2020-12-04 21:48 UTC, sandipsubedi approved these changes

2022-06-23 17:10 UTC, matthewhively commented
It would be nice to have this feature.

2026-08-30 15:05 UTC, PatrickTulskie requested changes
@h3nnn4n Hey I know this has been sitting for the better part of 6 years. I'm happy to get it merged if you're still interested. It could use a rebase and an update. Also, if you can remove the HISTORY.md change so that there aren't merge conflicts.

2026-08-30 15:05 UTC, PatrickTulskie commented on lib/resque/server.rb
> +      if params[:job_args].present?
This requires ActiveSupport, which we may not always have available.

2026-09-10 21:48 UTC, PatrickTulskie commented
I'm going to close this out as superseded by #1969 

We added a delete button for individual jobs in there, but did not add the "Remove Jobs" button at the top. Simple reason is that mass job deletion is brutal in resque as it sits. We also opened up ticket #1971 but I want to hold that until some variation of #1788 ships which may also require #1970 depending on what we settle on for architecture.

In any case, things are moving. The per-job delete button will go out in 3.1 and then we'll do some further optimizations to potentially land in 3.2. Thanks for the idea and your contribution!

2026-09-10 21:48 UTC, closed without merging