Ensure PIDFILE has pids of all running workers
resque/resque pull request #1733
Opened 2020-11-07 09:29 UTC by Z0Marlin

The workers now append to the PIDFILE instead of overwriting it.
Adding file locking to handle race conditions when multiple
workers are started using resque:workers.

To clear any older data in the specified PIDFILE, it is now truncated
once when the rake tasks resque:work and resque:workers are called.
Created a proxy task resque:run to achive this.

Fixes #1721

2020-11-30 15:29 UTC, Z0Marlin commented
ping

2021-11-08 13:44 UTC, iloveitaly requested changes
Could you help me understand the use case here more fully? I don't see why we have this task in the first place.

To get this merged:

* Could you respond to the message about why we aren't building the PIDFILE logic into `run`?
* Could you add a changelog entry?
* Rebase on master so CI runs

Thanks for the contribution!

2021-11-08 13:44 UTC, iloveitaly commented on lib/resque/tasks.rb
>    desc "Start multiple Resque workers. Should only be used in dev mode."
Do you understand the use case for this? Do you use this in production? Resque is designed around forking, so it seems strange that we support this. Also, shelling out to a rake task feels a bit dangerous to me for production-quality deployments.

2021-11-15 16:49 UTC, z0marlin commented
>Could you help me understand the use case here more fully? I don't see why we have this task in the first place.

Hey @iloveitaly! The issue this change tries to fix is #1721. We have a requirement to automate starting and stopping of resque workers. When starting multiple workers in the background, to stop each of the workers, we need the PIDs of the workers and so it would be great to have all the PIDs in the PIDFILE.

This is quite an old PR. I'll need some time to look at the changes I made and then I can address the comments. 

Thanks for reviewing the PR 😄

2022-01-31 19:33 UTC, iloveitaly commented
> This is quite an old PR. I'll need some time to look at the changes I made and then I can address the comments.

@z0marlin sound great!

2026-08-30 15:36 UTC, PatrickTulskie commented
Thanks for this, and apologies that it went quiet for so long.

That said, I'm going to close it, mainly over the PIDFILE semantics change: going from a single pid to newline-delimited pids will break anything currently reading that file expecting one value. It also restructures the task graph (resque:work becomes a wrapper around a new resque:run), which downstream Rakefiles may depend on. That's a wider compatibility surface than I want to take on without a major release or at least some sort of migration process for people.

The use case is reasonable, though. If you're still interested, I'd happily look at a fresh PR against current master that either writes a separate file for the multi-worker case and/or puts the new behavior behind an opt-in, so existing PIDFILE consumers are left alone.

In any case, I think for most multi-worker situations these days, people just use https://github.com/resque/resque-pool

2026-08-30 15:36 UTC, closed without merging