Update README with Rails example
resque/resque pull request #1735
Opened 2020-12-11 12:03 UTC by karpiu

I know the Rails case is in the wiki, but it took me awhile to figure this out, and in the meantime I was stuck. I even posted a question on stackoverflow:

https://stackoverflow.com/questions/65224796/resque-not-failing-an-obviously-buggy-job

And one of the users suggested I request this change, as the Rails is pretty popular case for the Resque gem.

2021-07-05 19:17 UTC, iloveitaly commented
@karpiu this is great! I think it would fit better as the last section within the "Jobs" header as opposed to right after the intro paragraph:

https://github.com/resque/resque#jobs

Could you move this around and ping me again on the PR?

2021-07-05 19:18 UTC, iloveitaly commented on README.markdown
> +If you installed the Resque as a Rails gem, the above example will look like this:
I think this should worded differently: resque is always going to be installed as a gem, and there's no such thing as a 'rails gem'. Maybe something like "If you are using ActiveJob here's how your job definition will look:"

2021-07-05 19:18 UTC, iloveitaly requested changes
@karpiu this is great! I think it would fit better as the last section within the "Jobs" header as opposed to right after the intro paragraph:

https://github.com/resque/resque#jobs

Could you move this around and ping me again on the PR?

2021-07-06 08:05 UTC, karpiu commented
Addressed comments @iloveitaly

2021-07-06 17:57 UTC, iloveitaly approved these changes
Great! Thank you.

2021-07-06 18:52 UTC, chrisccerami commented on README.markdown
> +Otherwise the Resque will process the job without actually doing anything.
I would remove the word `the` from between `Otherwise` and `Resque` to improve the grammar a bit.

2021-07-06 18:53 UTC, chrisccerami commented on README.markdown
> +Even if you put obviously buggy line like `0/0` in the `perform` method,
This is missing an article, like `Even if you put an obviously buggy line`.

2021-07-07 07:19 UTC, karpiu commented
@chrisccerami done

2021-07-07 15:59 UTC, chrisccerami commented
Thanks a lot @karpiu

2021-07-07 15:59 UTC, merged